env: Combat

env_args:
  gym_id: "Combat-v0"
  map_name: "all_scenario"
  full_observable: False
  n_agents: 5
  n_opponents: 5

mask_flag: False
global_state_flag: False
opp_action_in_cc: True
agent_level_batch_update: False