env: CooperativeStochasticGame

env_args:
  map_name: "all_scenario"
  num_agents: 4
  num_states: 30
  num_actions_per_agent: 4
  max_steps: 100

mask_flag: False
global_state_flag: False
opp_action_in_cc: True
agent_level_batch_update: False