env: PredatorPrey

env_args:
  gym_id: "PredatorPrey7x7-v0"
  map_name: "all_scenario"
  grid_shape: [7,7]
  n_agents: 4
  n_preys: 2
  penalty: -0.75

mask_flag: False
global_state_flag: False
opp_action_in_cc: True
agent_level_batch_update: False